### ISSUE TITLE
Local strategy

### ISSUE THREAD

**Issue by JurajJakubov** [andycmaj/nextjs-passport-session-auth#1]
Hello,

as one of beginners whos trying in free time to understand that crazy world of webdev it will be very helpful for all of us if it will be added local strategy with MongoDB for example that can help a lot of users to do a step they need and for me too.

Thanks anyway for this useful example it helps a lot :)

Geroge

**Comment by andycmaj** [comment]
Thanks! Glad it was useful...

@JurajJakubov do you mean mongoDB for doing user/password auth instead of using an OAuth strategy? 

I'm not sure there would be anything specific to next-js here that you couldn't find in a local-strategy-specific tutorial, eg. https://www.yudiz.com/passport-authentication-for-node-js-with-mongodb/.

the most interesting parts of this example have to do with how passport works with next-js's non-express api handlers/routes

**Comment by JurajJakubov** [comment]
Yes sorry is just lack of my knowledge in this area. I was looking for some example like nextjs connection with database, routing, folder structure and authentication local + one social with security(noslqi,xss,csrf...). but its something i can find online just dont want to make mistake :D
Thank again for this repo is very helpful.

Note: one good example in node + express auth local and social too if somebody needs - https://github.com/sahat/hackathon-starter
